---
- name: Install and Configure HashiCorp Vault and Vault UI
  hosts: vault
  become: yes
  tasks:
    - name: Install Required Packages
      dnf:
        name:
          - unzip
          - wget
          - dnf-plugins-core
        state: present

    - name: Add HashiCorp Repository
      command: dnf config-manager --add-repo=https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
      args:
        creates: /etc/yum.repos.d/hashicorp.repo

    - name: Install Vault
      dnf:
        name: vault
        state: present

    - name: Create Vault configuration directory
      file:
        path: /etc/vault.d
        state: directory

    - name: Create Vault Data directory
      file:
        path: /var/lib/vault/data
        state: directory
        owner: vault
        group: vault

    - name: Create Vault configuration file with UI enabled
      copy:
        dest: /etc/vault.d/vault.hcl
        content: |
          storage "file" {
            path = "/var/lib/vault/data"
          }
          listener "tcp" {
            address = "0.0.0.0:8200"
            tls_disable = 1
          }
          api_addr = "http://127.0.0.1:8200"
          ui = true
          cluster_addr = "http://127.0.0.1:8201"
        owner: root
        group: root
        mode: '0644'

    - name: Create a systemd service file for vault
      copy:
        dest: /etc/systemd/system/vault.service
        content: |
          [Unit]
          Description=HashiCorp Vault
          Documentation=https://www.vaultproject.io/docs/
          After=network-online.target

          [Service]
          User=vault
          Group=vault
          ExecStart=/usr/bin/vault server -config=/etc/vault.d/vault.hcl
          Restart=on-failure
          LimitNOFILE=65536

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload Systemd and Start Vault
      systemd:
        daemon_reload: yes
        name: vault
        state: started
        enabled: yes

